plugins:
  - uses:
    - plugin: https://ubiquity-os-comment-vector-embeddings-development.ubiquity.workers.dev
      with:
        matchThreshold: 0.95
        warningThreshold: 0.75
        jobMatchingThreshold: 0.75
  - uses:
    - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
      with:
        registerWalletWithVerification: false
  - uses:
    - plugin: https://command-query-user-development.ubiquity.workers.dev
      with:
        allowPublicQuery: true
  - uses:
    - plugin: https://ubiquibot-assistive-pricing-development.ubiquity.workers.dev
      with:
        labels:
          time:
            - "Time: <15 Minutes"
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
            - "Time: <2 Weeks"
            - "Time: <1 Month"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 2
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  - uses:
    - plugin: ubiquity-os-marketplace/conversation-rewards@development
      skipBotEvents: false
      with:
        logLevel: "debug"
        evmNetworkId: 100
        evmPrivateEncrypted: "gdo_iiUND1poZaibNme5oUsG1g8RDEmtI41uLgZjxW8WwxnQZb0DHkOBcISuwobxyKEyzeGQC9KzjkWXv0_OCv-kuUHy4myWNIhs4j3odyvh1XUP7pZFeuVEiASmKQBGkzlKRii5dA0liXtHnhciZQi5N8E7-cdOMbA" # https://github.com/ubiquibot/conversation-rewards/pull/111#issuecomment-2348639931
        erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
        incentives:
          requirePriceLabel: true
          contentEvaluator: {}
          userExtractor:
            enabled: true
            redeemTask: true
          dataPurge: {}
          formattingEvaluator:
            multipliers:
              - role:
                - ISSUE_SPECIFICATION
                multiplier: 3
                rewards:
                  wordValue: 0.1
              - role:
                - ISSUE_AUTHOR
                - ISSUE_COLLABORATOR
                - PULL_COLLABORATOR
                multiplier: 1
                rewards:
                  wordValue: 0.1
              - role:
                - ISSUE_CONTRIBUTOR
                - PULL_CONTRIBUTOR
                multiplier: 0.25
                rewards:
                  wordValue: 0.1
              - role:
                - PULL_SPECIFICATION
                - PULL_AUTHOR
                - ISSUE_ASSIGNEE
                - PULL_ASSIGNEE
                multiplier: 0
                rewards:
                  wordValue: 0
            wordCountExponent: 0.85
          permitGeneration:
            enabled: true
          githubComment:
            post: true
            debug: false
        dataCollection:
          maxAttempts: 10
          delayMs: 1000
  - uses:
    - plugin: ubiquity-os-marketplace/disqualifier@development
      with:
        warning: "3.5 days"
        disqualification: "7 days"
        watch:
          optOut:
            - ubiquibot
            - launch-party
            - staging
            - production
  - uses:
    - plugin: ubiquity-os-marketplace/automated-merging@development
      with:
        approvalsRequired:
          collaborator: 1
          contributor: 2
        mergeTimeout:
          collaborator: "3.5 days"
          contributor: "7 days"
        repos:
          monitor: []
          ignore:
            - ubiquibot
            - launch-party
            - staging
            - production
        allowedReviewerRoles:
          - COLLABORATOR
          - MEMBER
          - OWNER
  - uses:
    - plugin: https://ubiquibot-command-start-stop-development.ubiquity.workers.dev
      with:
        reviewDelayTolerance: "3 Days"
        taskStaleTimeoutDuration: "30 Days"
        startRequiresWallet: true
        maxConcurrentTasks:
          member: 2
          contributor: 2
        emptyWalletText: "Please set your wallet address with the /wallet command first and try again."
        rolesWithReviewAuthority:
          - COLLABORATOR
          - OWNER
          - MEMBER
          - ADMIN